### PR TITLE
DPM case study

### PR DESCRIPTION
**Pull request by Luke-Shaw**
Adding case-studies/posts/2024/05/03/dpm.html

### CODE REVIEW

**Comment by brtarran** [comment]
@RoyalStatisticalSociety This case study was out for second review with the RWDS editorial board at the time I left RSS. I can connect you with the reviewers if needed.

**Comment by RoyalStatisticalSociety** [comment]
@brtarran just to clarify we are adding a new folder and article under case studies/posts? 
do we need to approve this as well?

Screenshot 2024-04-19 160140

**Comment by Luke-Shaw** [comment]
@RoyalStatisticalSociety yes it's a new case-study post, that is what has been reviewed. New page is is `case-studies/posts/2024/05/03/dpm.html`

Perhaps you'll want to amend the folder path to the date when it is reviewed eg if today change all from  `case-studies/posts/2024/05/03/` to  `case-studies/posts/2024/05/08/`

**Comment by brtarran** [comment]
@Luke-Shaw render has failed because of the code chunk being used to produce a table in the qmd. Advise removing the code and inserting the table as markdown using RStudio visual editor.

**Comment by Luke-Shaw** [comment]
@RoyalStatisticalSociety thanks for scheduling the task. It looks like the job failed with [message](https://github.com/realworlddatascience/realworlddatascience.github.io/actions/runs/8983083175/job/24738633876) _Error in loadNamespace(x) : there is no package called ‘rmarkdown’_

I think adding this in line 26 of `dpm.qmd` might resolve the problem:

```{r}
#| label: package-setup
if(!require(rmarkdown)){
    install.packages("rmarkdown")
    library(rmarkdown)}
```

But I'm not sure. It is perhaps easiest to try and resolve over a call? I'm available all day this Friday (10th). Email address is prefix l.shaw4 suffix nhs.net with an @ joining them - if you'd like to schedule a call.

**Comment by Luke-Shaw** [comment]
@brtarran @RoyalStatisticalSociety thanks - I have made the change you suggested Brian in [86c2f11](https://github.com/realworlddatascience/realworlddatascience.github.io/pull/178/commits/86c2f1149b06ec22b4af5461fe2e3915c9a10bee) on this pull request thread. Can we try reviewing and running the checks again please?

**Comment by RoyalStatisticalSociety** [comment]
@Luke-Shaw @brtarran  checks have passed If everyone is happy I'll merge the pull request

**Review by RoyalStatisticalSociety — APPROVED** [review]

**Pull request merged**
